# SPDX-License-Identifier: AGPL-3.0-only
# The configuration of what k3s and the controllers installed.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik.yaml
  - service-accounts.yaml
