# SPDX-License-Identifier: AGPL-3.0-only
# The default service accounts of the namespaces Kubernetes makes itself:
# a pod that names no account of its own gets no token for the API (k3s
# CIS hardening guide; CIS Kubernetes Benchmark, "default service accounts
# are not actively used"). The game's pods mount none either.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: kube-node-lease
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: kube-public
automountServiceAccountToken: false
