# SPDX-License-Identifier: AGPL-3.0-only
# Plain HTTP answers with a permanent redirect to HTTPS, for whatever name
# the request used.
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  namespace: keel
spec:
  parentRefs:
    - name: keel
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
