# SPDX-License-Identifier: AGPL-3.0-only
# keel in 8 GiB: half production's memory, but the same CPU limit, which
# sets GOMAXPROCS and so the encoders and physics workers. The pull policy
# is Kubernetes' own for an image named by digest, said outright: a deploy
# from the working tree sets Never, for the image it imports, and a release
# applied after it must take the field back.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keel
  namespace: keel
spec:
  template:
    spec:
      initContainers:
        - name: migrate
          imagePullPolicy: IfNotPresent
      containers:
        - name: keel
          imagePullPolicy: IfNotPresent
          env:
            - name: GOMEMLIMIT
              value: 1800MiB
          resources:
            requests:
              cpu: "1"
              memory: 2Gi
            limits:
              cpu: "3"
              memory: 2Gi
