# SPDX-License-Identifier: AGPL-3.0-only
- name: Load the kernel settings
  ansible.builtin.command:
    cmd: sysctl --quiet --system
  changed_when: true

- name: Restart journald
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted

- name: Restart resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: restarted
