// SPDX-License-Identifier: AGPL-3.0-only

// The catalog of kinds. The data and its types are generated by
// tools/catalog; never edit them by hand.

import data from './catalog.gen.json';
import type { Catalog } from './types.gen';

export type { Boat, Catalog } from './types.gen';
export { CATALOG_VERSION } from './types.gen';

export const catalog = data as Catalog;
