// SPDX-License-Identifier: AGPL-3.0-only
// Code generated by tools/catalog from shared/catalog.schema.json. DO NOT EDIT.

/**
 * Stable identifier of a kind, stored in the database: never renamed or reused.
 *
 * This interface was referenced by `Catalog`'s JSON-Schema
 * via the `definition` "Id".
 */
export type Id = string;

/**
 * Every list of kinds in the game. Kinds are data: code reads their properties, never their names.
 */
export interface Catalog {
  /**
   * Boat types.
   *
   * @minItems 1
   */
  boats: [Boat, ...Boat[]];
}
/**
 * This interface was referenced by `Catalog`'s JSON-Schema
 * via the `definition` "Boat".
 */
export interface Boat {
  id: Id;
  /**
   * Display name.
   */
  name: string;
  /**
   * What the boat is, in a few words.
   */
  description: string;
  /**
   * Most people aboard, the skipper included.
   */
  capacity: number;
  /**
   * Length overall, in metres.
   */
  lengthOverall: number;
  art?: Art;
}
/**
 * Paths of a kind's art files, relative to the repository's art/ folder.
 *
 * This interface was referenced by `Catalog`'s JSON-Schema
 * via the `definition` "Art".
 */
export interface Art {
  [k: string]: string;
}

/** The catalog version (tools/catalog). */
export const CATALOG_VERSION = '1062915e6cb9a2d8';
