# SPDX-License-Identifier: AGPL-3.0-only
# Pod Security's restricted profile is warned and audited, not yet enforced.
apiVersion: v1
kind: Namespace
metadata:
  name: keel
  labels:
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
