// SPDX-License-Identifier: AGPL-3.0-only

// Command confusables generates the look-alike table sailor names are
// compared by, internal/moderation/confusables.gen.go, from Unicode's
// confusables.txt (UTS #39, Unicode Security Mechanisms), committed here with
// Unicode's licence. The file is pinned by version and SHA-256, and its
// version matches the Unicode version of golang.org/x/text's normalisation
// tables: the two move together.
//
//	go run ./tools/confusables          write the table
//	go run ./tools/confusables -check   fail if the table is not what the file gives
//
// It fetches nothing. It runs from the repository root.
package main

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"slices"
	"strconv"
	"strings"
	"unicode"
)

const (
	version = "17.0.0"
	source  = "tools/confusables/confusables-" + version + ".txt"
	// sourceSHA256 is the SHA-256 of confusables.txt as Unicode publishes it,
	// at https://www.unicode.org/Public/17.0.0/security/confusables.txt.
	sourceSHA256 = "091c7f82fc39ef208faf8f94d29c244de99254675e09de163160c810d13ef22a"
	out          = "internal/moderation/confusables.gen.go"
)

func main() {
	check := flag.Bool("check", false, "fail if the generated table is not current")
	flag.Parse()
	if err := run(*check); err != nil {
		fmt.Fprintln(os.Stderr, "confusables:", err)
		os.Exit(1)
	}
}

func run(check bool) error {
	data, err := os.ReadFile(source)
	if err != nil {
		return err
	}
	gen, err := generate(data)
	if err != nil {
		return err
	}
	if check {
		old, err := os.ReadFile(out)
		if err != nil {
			return err
		}
		if !bytes.Equal(old, gen) {
			return fmt.Errorf("%s is not what %s gives: go run ./tools/confusables", out, source)
		}
		fmt.Println("confusables: the table is current")
		return nil
	}
	return os.WriteFile(out, gen, 0o644)
}

type entry struct {
	from rune
	to   string
}

// generate checks data against the pinned digest and writes the table.
func generate(data []byte) ([]byte, error) {
	sum := sha256.Sum256(data)
	if got := hex.EncodeToString(sum[:]); got != sourceSHA256 {
		return nil, fmt.Errorf("%s has SHA-256 %s, not the pinned %s", source, got, sourceSHA256)
	}
	entries, err := parse(data)
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString("// SPDX-License-Identifier: AGPL-3.0-only AND Unicode-3.0\n")
	fmt.Fprintf(&b, "// Code generated by tools/confusables from Unicode's confusables.txt %s. DO NOT EDIT.\n", version)
	b.WriteString("// The data is Unicode's, under the Unicode License v3 (tools/confusables/LICENSE).\n\n")
	b.WriteString("package moderation\n\n")
	fmt.Fprintf(&b, "// confusablesVersion is the Unicode version of the look-alike table.\nconst confusablesVersion = %q\n\n", version)
	b.WriteString("// confusables maps each character that has one to its prototype, the\n")
	b.WriteString("// string it is confusable with, sorted by character (UTS #39, section 4).\n")
	b.WriteString("var confusables = [...]confusable{\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "\t{0x%04X, %s},\n", e.from, strconv.QuoteToASCII(e.to))
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

// parse reads lines of "source ; target ; type # comment", each source one
// code point and each target one or more, in hexadecimal.
func parse(data []byte) ([]entry, error) {
	var entries []entry
	sc := bufio.NewScanner(bytes.NewReader(data))
	for n := 1; sc.Scan(); n++ {
		line := sc.Text()
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		if strings.TrimSpace(line) == "" {
			continue
		}
		fields := strings.Split(line, ";")
		if len(fields) != 3 {
			return nil, fmt.Errorf("line %d: %d fields", n, len(fields))
		}
		from, err := codePoints(fields[0])
		if err != nil || len(from) != 1 {
			return nil, fmt.Errorf("line %d: the source is not one code point: %q", n, fields[0])
		}
		to, err := codePoints(fields[1])
		if err != nil || len(to) == 0 {
			return nil, fmt.Errorf("line %d: the target: %q", n, fields[1])
		}
		entries = append(entries, entry{from: from[0], to: string(to)})
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	if len(entries) == 0 {
		return nil, errors.New("no entries")
	}
	slices.SortFunc(entries, func(a, b entry) int { return int(a.from - b.from) })
	for i := 1; i < len(entries); i++ {
		if entries[i].from == entries[i-1].from {
			return nil, fmt.Errorf("U+%04X is listed twice", entries[i].from)
		}
	}
	return entries, nil
}

func codePoints(s string) ([]rune, error) {
	var rs []rune
	for f := range strings.FieldsSeq(s) {
		v, err := strconv.ParseUint(f, 16, 32)
		if err != nil {
			return nil, err
		}
		if v > unicode.MaxRune {
			return nil, fmt.Errorf("%s is not a code point", f)
		}
		rs = append(rs, rune(v))
	}
	return rs, nil
}
