// SPDX-License-Identifier: AGPL-3.0-only

// The game connection's control messages. Each WebSocket binary message is
// one game message whose first byte is its kind (snapshot.txt): kind 1 is
// one of the envelopes below, encoded as Protocol Buffers; kind 2 is the
// packed snapshot, which is not described here.
//
// go run ./tools/protocol generates the Go and TypeScript from this file,
// and the protocol version from this file and snapshot.txt.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: keel/v1/game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientMessage is everything a client sends, after the kind byte 1.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ClientMessage_Hello
	//	*ClientMessage_Input
	//	*ClientMessage_Ping
	//	*ClientMessage_Command
	Body          isClientMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_keel_v1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_keel_v1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_keel_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetBody() isClientMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientMessage) GetInput() *Input {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *ClientMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ClientMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isClientMessage_Body interface {
	isClientMessage_Body()
}

type ClientMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ClientMessage_Input struct {
	Input *Input `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

type ClientMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type ClientMessage_Command struct {
	Command *Command `protobuf:"bytes,4,opt,name=command,proto3,oneof"`
}

func (*ClientMessage_Hello) isClientMessage_Body() {}

func (*ClientMessage_Input) isClientMessage_Body() {}

func (*ClientMessage_Ping) isClientMessage_Body() {}

func (*ClientMessage_Command) isClientMessage_Body() {}

// Hello is the first message on a connection. A client whose protocol,
// catalog or physics layout differs from the server's is closed with 4002.
type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The protocol version: a hash of the schema and the snapshot's layout.
	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// The catalog version the client was built with.
	Catalog string `protobuf:"bytes,2,opt,name=catalog,proto3" json:"catalog,omitempty"`
	// The physics module's layout version.
	PhysicsLayout uint32 `protobuf:"varint,3,opt,name=physics_layout,json=physicsLayout,proto3" json:"physics_layout,omitempty"`
	// The client's build, for the log only.
	Build         string `protobuf:"bytes,4,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_keel_v1_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_keel_v1_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_keel_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Hello) GetCatalog() string {
	if x != nil {
		return x.Catalog
	}
	return ""
}

func (x *Hello) GetPhysicsLayout() uint32 {
	if x != nil {
		return x.PhysicsLayout
	}
	return 0
}

func (x *Hello) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

// Input is the controls the client steps its boat with, stamped with the
// tick it predicted them for; or, with ack_only, just an acknowledgement.
type Input struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The low 32 bits of the tick the controls are for.
	Seq uint32 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// The helm, 0 (hard to port) to 1024 (hard to starboard).
	Helm uint32 `protobuf:"varint,2,opt,name=helm,proto3" json:"helm,omitempty"`
	// The sheet, 0 (hauled in) to 1024 (let fly).
	Sheet uint32 `protobuf:"varint,3,opt,name=sheet,proto3" json:"sheet,omitempty"`
	// The tick of the newest snapshot the client has decoded; 0 for none.
	AckTick int64 `protobuf:"varint,4,opt,name=ack_tick,json=ackTick,proto3" json:"ack_tick,omitempty"`
	// No control change: the message only acknowledges.
	AckOnly       bool `protobuf:"varint,5,opt,name=ack_only,json=ackOnly,proto3" json:"ack_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_keel_v1_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_keel_v1_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_keel_v1_game_proto_rawDescGZIP(), []int{2}
}

func (x *Input) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Input) GetHelm() uint32 {
	if x != nil {
		return x.Helm
	}
	return 0
}

func (x *Input) GetSheet() uint32 {
	if x != nil {
		return x.Sheet
	}
	return 0
}

func (x *Input) GetAckTick() int64 {
	if x != nil {
		return x.AckTick
	}
	return 0
}

func (x *Input) GetAckOnly() bool {
	if x != nil {
		return x.AckOnly
	}
	return false
}

// Ping asks for the server's world time, for the client's clock.
type Ping struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The client's own clock, in microseconds; returned in the Pong.
	ClientTimeUs int64 `protobuf:"varint,1,opt,name=client_time_us,json=clientTimeUs,proto3" json:"client_time_us,omitempty"`
	// The tick of the newest snapshot the client has decoded; 0 for none.
	AckTick int64 `protobuf:"varint,2,opt,name=ack_tick,json=ackTick,proto3" json:"ack_tick,omitempty"`
	// The client's estimate of the round trip, in milliseconds.
	RttMs uint32 `protobuf:"varint,3,opt,name=rtt_ms,json=rttMs,proto3" json:"rtt_ms,omitempty"`
	// The 95th percentile of the client's frame time, in milliseconds.
	FrameMs       uint32 `protobuf:"varint,4,opt,name=frame_ms,json=frameMs,proto3" json:"frame_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_keel_v1_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_keel_v1_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_keel_v1_game_proto_rawDescGZIP(), []int{3}
}

func (x *Ping) GetClientTimeUs() int64 {
	if x != nil {
		return x.ClientTimeUs
	}
	return 0
}

func (x *Ping) GetAckTick() int64 {
	if x != nil {
		return x.AckTick
	}
	return 0
}

func (x *Ping) GetRttMs() uint32 {
	if x != nil {
		return x.RttMs
	}
	return 0
}

func (x *Ping) GetFrameMs() uint32 {
	if x != nil {
		return x.FrameMs
	}
	return 0
}

// Command is something the player asks of the game.
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Command_Resync
	Body          isCommand_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_keel_v1_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_keel_v1_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_keel_v1_game_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetBody() isCommand_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Command) GetResync() *Resync {
	if x != nil {
		if x, ok := x.Body.(*Command_Resync); ok {
			return x.Resync
		}
	}
	return nil
}

type isCommand_Body interface {
	isCommand_Body()
}

type Command_Resync struct {
	Resync *Resync `protobuf:"bytes,1,opt,name=resync,proto3,oneof"`
}

func (*Command_Resync) isCommand_Body() {}

// Resync asks for the next snapshot in full: the client lacks the base of
// one it received. At most one a second is honoured.
type Resync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resync) Reset() {
	*x = Resync{}
	mi := &file_keel_v1_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resync) ProtoMessage() {}

func (x *Resync) ProtoReflect() protoreflect.Message {
	mi := &file_keel_v1_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resync.ProtoReflect.Descriptor instead.
func (*Resync) Descriptor() ([]byte, []int) {
	return file_keel_v1_game_proto_rawDescGZIP(), []int{5}
}

// ServerMessage is everything the server sends but snapshots, after the
// kind byte 1.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerMessage_Welcome
	//	*ServerMessage_Pong
	//	*ServerMessage_Queued
	Body          isServerMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_keel_v1_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_keel_v1_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_keel_v1_game_proto_rawDescGZIP(), []int{6}
}

func (x *ServerMessage) GetBody() isServerMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ServerMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ServerMessage) GetQueued() *Queued {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Queued); ok {
			return x.Queued
		}
	}
	return nil
}

type isServerMessage_Body interface {
	isServerMessage_Body()
}

type ServerMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ServerMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,2,opt,name=pong,proto3,oneof"`
}

type ServerMessage_Queued struct {
	Queued *Queued `protobuf:"bytes,3,opt,name=queued,proto3,oneof"`
}

func (*ServerMessage_Welcome) isServerMessage_Body() {}

func (*ServerMessage_Pong) isServerMessage_Body() {}

func (*ServerMessage_Queued) isServerMessage_Body() {}

// Queued says the sea is full: the client waits for a boat. It comes after
// the Hello, and again whenever the place changes, at most once a second;
// a Welcome follows when the boat is given.
type Queued struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The place in the queue, 1 for the next to be given a boat.
	Position uint32 `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	// How many wait in all.
	Waiting       uint32 `protobuf:"varint,2,opt,name=waiting,proto3" json:"waiting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Queued) Reset() {
	*x = Queued{}
	mi := &file_keel_v1_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queued) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queued) ProtoMessage() {}

func (x *Queued) ProtoReflect() protoreflect.Message {
	mi := &file_keel_v1_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queued.ProtoReflect.Descriptor instead.
func (*Queued) Descriptor() ([]byte, []int) {
	return file_keel_v1_game_proto_rawDescGZIP(), []int{7}
}

func (x *Queued) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Queued) GetWaiting() uint32 {
	if x != nil {
		return x.Waiting
	}
	return 0
}

// Welcome says the client has its boat; its snapshots follow.
type Welcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The world's ID.
	World string `protobuf:"bytes,1,opt,name=world,proto3" json:"world,omitempty"`
	// The tick of the first frame the boat was in.
	Tick int64 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	// World time when sent: microseconds since the world's epoch.
	WorldTimeUs int64 `protobuf:"varint,3,opt,name=world_time_us,json=worldTimeUs,proto3" json:"world_time_us,omitempty"`
	// The boat's ID.
	Boat uint64 `protobuf:"varint,4,opt,name=boat,proto3" json:"boat,omitempty"`
	// The boat's kind: an index into the catalog's boats.
	Kind uint32 `protobuf:"varint,5,opt,name=kind,proto3" json:"kind,omitempty"`
	// The boat is the one the account already had.
	Rejoined      bool `protobuf:"varint,6,opt,name=rejoined,proto3" json:"rejoined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_keel_v1_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_keel_v1_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_keel_v1_game_proto_rawDescGZIP(), []int{8}
}

func (x *Welcome) GetWorld() string {
	if x != nil {
		return x.World
	}
	return ""
}

func (x *Welcome) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *Welcome) GetWorldTimeUs() int64 {
	if x != nil {
		return x.WorldTimeUs
	}
	return 0
}

func (x *Welcome) GetBoat() uint64 {
	if x != nil {
		return x.Boat
	}
	return 0
}

func (x *Welcome) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *Welcome) GetRejoined() bool {
	if x != nil {
		return x.Rejoined
	}
	return false
}

// Pong answers a Ping.
type Pong struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Ping's client_time_us.
	ClientTimeUs int64 `protobuf:"varint,1,opt,name=client_time_us,json=clientTimeUs,proto3" json:"client_time_us,omitempty"`
	// World time when sent: microseconds since the world's epoch.
	WorldTimeUs   int64 `protobuf:"varint,2,opt,name=world_time_us,json=worldTimeUs,proto3" json:"world_time_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_keel_v1_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_keel_v1_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_keel_v1_game_proto_rawDescGZIP(), []int{9}
}

func (x *Pong) GetClientTimeUs() int64 {
	if x != nil {
		return x.ClientTimeUs
	}
	return 0
}

func (x *Pong) GetWorldTimeUs() int64 {
	if x != nil {
		return x.WorldTimeUs
	}
	return 0
}

var File_keel_v1_game_proto protoreflect.FileDescriptor

const file_keel_v1_game_proto_rawDesc = "" +
	"\n" +
	"\x12keel/v1/game.proto\x12\akeel.v1\"\xba\x01\n" +
	"\rClientMessage\x12&\n" +
	"\x05hello\x18\x01 \x01(\v2\x0e.keel.v1.HelloH\x00R\x05hello\x12&\n" +
	"\x05input\x18\x02 \x01(\v2\x0e.keel.v1.InputH\x00R\x05input\x12#\n" +
	"\x04ping\x18\x03 \x01(\v2\r.keel.v1.PingH\x00R\x04ping\x12,\n" +
	"\acommand\x18\x04 \x01(\v2\x10.keel.v1.CommandH\x00R\acommandB\x06\n" +
	"\x04body\"z\n" +
	"\x05Hello\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x18\n" +
	"\acatalog\x18\x02 \x01(\tR\acatalog\x12%\n" +
	"\x0ephysics_layout\x18\x03 \x01(\rR\rphysicsLayout\x12\x14\n" +
	"\x05build\x18\x04 \x01(\tR\x05build\"y\n" +
	"\x05Input\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\rR\x03seq\x12\x12\n" +
	"\x04helm\x18\x02 \x01(\rR\x04helm\x12\x14\n" +
	"\x05sheet\x18\x03 \x01(\rR\x05sheet\x12\x19\n" +
	"\back_tick\x18\x04 \x01(\x03R\aackTick\x12\x19\n" +
	"\back_only\x18\x05 \x01(\bR\aackOnly\"y\n" +
	"\x04Ping\x12$\n" +
	"\x0eclient_time_us\x18\x01 \x01(\x03R\fclientTimeUs\x12\x19\n" +
	"\back_tick\x18\x02 \x01(\x03R\aackTick\x12\x15\n" +
	"\x06rtt_ms\x18\x03 \x01(\rR\x05rttMs\x12\x19\n" +
	"\bframe_ms\x18\x04 \x01(\rR\aframeMs\"<\n" +
	"\aCommand\x12)\n" +
	"\x06resync\x18\x01 \x01(\v2\x0f.keel.v1.ResyncH\x00R\x06resyncB\x06\n" +
	"\x04body\"\b\n" +
	"\x06Resync\"\x95\x01\n" +
	"\rServerMessage\x12,\n" +
	"\awelcome\x18\x01 \x01(\v2\x10.keel.v1.WelcomeH\x00R\awelcome\x12#\n" +
	"\x04pong\x18\x02 \x01(\v2\r.keel.v1.PongH\x00R\x04pong\x12)\n" +
	"\x06queued\x18\x03 \x01(\v2\x0f.keel.v1.QueuedH\x00R\x06queuedB\x06\n" +
	"\x04body\">\n" +
	"\x06Queued\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\rR\bposition\x12\x18\n" +
	"\awaiting\x18\x02 \x01(\rR\awaiting\"\x9b\x01\n" +
	"\aWelcome\x12\x14\n" +
	"\x05world\x18\x01 \x01(\tR\x05world\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\x03R\x04tick\x12\"\n" +
	"\rworld_time_us\x18\x03 \x01(\x03R\vworldTimeUs\x12\x12\n" +
	"\x04boat\x18\x04 \x01(\x04R\x04boat\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\rR\x04kind\x12\x1a\n" +
	"\brejoined\x18\x06 \x01(\bR\brejoined\"P\n" +
	"\x04Pong\x12$\n" +
	"\x0eclient_time_us\x18\x01 \x01(\x03R\fclientTimeUs\x12\"\n" +
	"\rworld_time_us\x18\x02 \x01(\x03R\vworldTimeUsB=Z;github.com/daneelvt/keel-over-the-edge/internal/protocol/pbb\x06proto3"

var (
	file_keel_v1_game_proto_rawDescOnce sync.Once
	file_keel_v1_game_proto_rawDescData []byte
)

func file_keel_v1_game_proto_rawDescGZIP() []byte {
	file_keel_v1_game_proto_rawDescOnce.Do(func() {
		file_keel_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keel_v1_game_proto_rawDesc), len(file_keel_v1_game_proto_rawDesc)))
	})
	return file_keel_v1_game_proto_rawDescData
}

var file_keel_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_keel_v1_game_proto_goTypes = []any{
	(*ClientMessage)(nil), // 0: keel.v1.ClientMessage
	(*Hello)(nil),         // 1: keel.v1.Hello
	(*Input)(nil),         // 2: keel.v1.Input
	(*Ping)(nil),          // 3: keel.v1.Ping
	(*Command)(nil),       // 4: keel.v1.Command
	(*Resync)(nil),        // 5: keel.v1.Resync
	(*ServerMessage)(nil), // 6: keel.v1.ServerMessage
	(*Queued)(nil),        // 7: keel.v1.Queued
	(*Welcome)(nil),       // 8: keel.v1.Welcome
	(*Pong)(nil),          // 9: keel.v1.Pong
}
var file_keel_v1_game_proto_depIdxs = []int32{
	1, // 0: keel.v1.ClientMessage.hello:type_name -> keel.v1.Hello
	2, // 1: keel.v1.ClientMessage.input:type_name -> keel.v1.Input
	3, // 2: keel.v1.ClientMessage.ping:type_name -> keel.v1.Ping
	4, // 3: keel.v1.ClientMessage.command:type_name -> keel.v1.Command
	5, // 4: keel.v1.Command.resync:type_name -> keel.v1.Resync
	8, // 5: keel.v1.ServerMessage.welcome:type_name -> keel.v1.Welcome
	9, // 6: keel.v1.ServerMessage.pong:type_name -> keel.v1.Pong
	7, // 7: keel.v1.ServerMessage.queued:type_name -> keel.v1.Queued
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_keel_v1_game_proto_init() }
func file_keel_v1_game_proto_init() {
	if File_keel_v1_game_proto != nil {
		return
	}
	file_keel_v1_game_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Hello)(nil),
		(*ClientMessage_Input)(nil),
		(*ClientMessage_Ping)(nil),
		(*ClientMessage_Command)(nil),
	}
	file_keel_v1_game_proto_msgTypes[4].OneofWrappers = []any{
		(*Command_Resync)(nil),
	}
	file_keel_v1_game_proto_msgTypes[6].OneofWrappers = []any{
		(*ServerMessage_Welcome)(nil),
		(*ServerMessage_Pong)(nil),
		(*ServerMessage_Queued)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keel_v1_game_proto_rawDesc), len(file_keel_v1_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keel_v1_game_proto_goTypes,
		DependencyIndexes: file_keel_v1_game_proto_depIdxs,
		MessageInfos:      file_keel_v1_game_proto_msgTypes,
	}.Build()
	File_keel_v1_game_proto = out.File
	file_keel_v1_game_proto_goTypes = nil
	file_keel_v1_game_proto_depIdxs = nil
}
