// SPDX-License-Identifier: AGPL-3.0-only

// Package catalog holds the catalog of kinds, such as boat types. Kinds are
// data: code reads their properties, never their names. The data and its types
// are generated by tools/catalog from shared/; never edit them by hand.
package catalog

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"io"
)

//go:embed catalog.gen.json
var embedded []byte

// Load decodes the catalog built into the binary.
func Load() (*Catalog, error) {
	return Parse(embedded)
}

// Parse decodes a catalog strictly: unknown fields and trailing data are
// errors, so a server never runs with data it does not understand.
func Parse(data []byte) (*Catalog, error) {
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	var c Catalog
	if err := dec.Decode(&c); err != nil {
		return nil, fmt.Errorf("catalog: %w", err)
	}
	if _, err := dec.Token(); !errors.Is(err, io.EOF) {
		return nil, errors.New("catalog: unexpected data after the catalog")
	}
	if len(c.Boats) == 0 {
		return nil, errors.New("catalog: no boats")
	}
	return &c, nil
}
