// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by tools/catalog from shared/catalog.schema.json. DO NOT EDIT.

package catalog

import "github.com/daneelvt/keel-over-the-edge/internal/physics"

// PhysicsParams returns a boat's physics values as the physics package's
// Params.
func PhysicsParams(b *Boat) physics.Params {
	var p physics.Params
	p.Displacement = b.Physics.Hull.Displacement
	p.WaterlineLength = b.Physics.Hull.WaterlineLength
	p.HullDraught = b.Physics.Hull.HullDraught
	p.CentreOfGravity = b.Physics.Hull.CentreOfGravity
	p.DragAreaStep = b.Physics.Hull.DragAreaStep
	copy(p.DragArea[:], b.Physics.Hull.DragArea)
	p.CrossFlowDrag = b.Physics.Hull.CrossFlowDrag
	p.AddedMassSurge = b.Physics.Hull.AddedMassSurge
	p.AddedMassSway = b.Physics.Hull.AddedMassSway
	p.Munk = b.Physics.Hull.Munk
	p.YawInertia = b.Physics.Hull.YawInertia
	p.RollInertia = b.Physics.Hull.RollInertia
	p.RollDamping = b.Physics.Hull.RollDamping
	copy(p.RightingLever[:], b.Physics.Hull.RightingLever)
	p.SailArea = b.Physics.Rig.SailArea
	p.Luff = b.Physics.Rig.Luff
	p.Foot = b.Physics.Rig.Foot
	p.BoomHeight = b.Physics.Rig.BoomHeight
	p.MastPosition = b.Physics.Rig.MastPosition
	p.FootStrip = b.Physics.Rig.FootStrip
	p.HeadStrip = b.Physics.Rig.HeadStrip
	p.PressureAttached = b.Physics.Rig.PressureAttached
	p.PressureSeparated = b.Physics.Rig.PressureSeparated
	p.EffectiveHeight = b.Physics.Rig.EffectiveHeight
	p.QuadraticDrag = b.Physics.Rig.QuadraticDrag
	p.MaxLift = b.Physics.Rig.MaxLift
	p.StallAngle = b.Physics.Rig.StallAngle
	p.StallWidth = b.Physics.Rig.StallWidth
	p.SailDrag = b.Physics.Rig.SailDrag
	p.LuffAngle = b.Physics.Rig.LuffAngle
	p.FlogDrag = b.Physics.Rig.FlogDrag
	copy(p.NormalForce[:], b.Physics.Rig.NormalForce)
	p.TwistPowered = b.Physics.Rig.TwistPowered
	p.TwistDepowered = b.Physics.Rig.TwistDepowered
	p.TwistEased = b.Physics.Rig.TwistEased
	p.TwistTurn = b.Physics.Rig.TwistTurn
	p.HeadBacked = b.Physics.Rig.HeadBacked
	p.HeadBackedWidth = b.Physics.Rig.HeadBackedWidth
	p.BoomIn = b.Physics.Rig.BoomIn
	p.BoomOut = b.Physics.Rig.BoomOut
	p.BoomInertia = b.Physics.Rig.BoomInertia
	p.BoomMoment = b.Physics.Rig.BoomMoment
	p.BoomDamping = b.Physics.Rig.BoomDamping
	p.WindageFront = b.Physics.Rig.WindageFront
	p.WindageSide = b.Physics.Rig.WindageSide
	p.WindageHeight = b.Physics.Rig.WindageHeight
	p.SailFloat = b.Physics.Rig.SailFloat
	p.SailWaterDamping = b.Physics.Rig.SailWaterDamping
	p.BoardSpan = b.Physics.Foils.BoardSpan
	p.BoardChord = b.Physics.Foils.BoardChord
	p.BoardPosition = b.Physics.Foils.BoardPosition
	p.RudderSpan = b.Physics.Foils.RudderSpan
	p.RudderChord = b.Physics.Foils.RudderChord
	p.RudderPosition = b.Physics.Foils.RudderPosition
	p.RudderAngle = b.Physics.Foils.RudderAngle
	p.FoilStall = b.Physics.Foils.FoilStall
	p.FoilStallWidth = b.Physics.Foils.FoilStallWidth
	p.FoilDrag = b.Physics.Foils.FoilDrag
	p.PlateNormal = b.Physics.Foils.PlateNormal
	p.PressureDepth = b.Physics.Foils.PressureDepth
	p.CarryOver = b.Physics.Foils.CarryOver
	p.HeelLoss = b.Physics.Foils.HeelLoss
	p.RudderInflow = b.Physics.Foils.RudderInflow
	p.Downwash = b.Physics.Foils.Downwash
	p.FoilWetHeel = b.Physics.Foils.FoilWetHeel
	p.FoilDryHeel = b.Physics.Foils.FoilDryHeel
	p.SailorMass = b.Physics.Sailor.SailorMass
	p.SailorSeatHeight = b.Physics.Sailor.SailorSeatHeight
	p.HikeReach = b.Physics.Sailor.HikeReach
	p.LeeReach = b.Physics.Sailor.LeeReach
	p.HikeSpeed = b.Physics.Sailor.HikeSpeed
	p.HikeLag = b.Physics.Sailor.HikeLag
	p.HeelGain = b.Physics.Sailor.HeelGain
	p.RollRateGain = b.Physics.Sailor.RollRateGain
	p.FlattenFrom = b.Physics.Sailor.FlattenFrom
	p.FlattenTo = b.Physics.Sailor.FlattenTo
	p.FlattenMin = b.Physics.Sailor.FlattenMin
	p.FallOutHeel = b.Physics.Sailor.FallOutHeel
	p.ClimbInHeel = b.Physics.Sailor.ClimbInHeel
	p.BoardReach = b.Physics.Sailor.BoardReach
	p.SailorDrag = b.Physics.Sailor.SailorDrag
	p.SwimTime = b.Physics.Sailor.SwimTime
	p.ClimbTime = b.Physics.Sailor.ClimbTime
	p.RudderTime = b.Physics.Rates.RudderTime
	p.SheetHaulTime = b.Physics.Rates.SheetHaulTime
	p.SheetEaseTime = b.Physics.Rates.SheetEaseTime
	return p
}
