// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package catalog

// Paths of a kind's art files, relative to the repository's art/ folder.
type Art map[string]string

type Boat struct {
	// Art corresponds to the JSON schema field "art".
	Art Art `json:"art,omitempty,omitzero"`

	// Most people aboard, the skipper included.
	Capacity int `json:"capacity"`

	// What the boat is, in a few words.
	Description string `json:"description"`

	// ID corresponds to the JSON schema field "id".
	ID ID `json:"id"`

	// Length overall, in metres.
	LengthOverall float64 `json:"lengthOverall"`

	// Display name.
	Name string `json:"name"`
}

// Every list of kinds in the game. Kinds are data: code reads their properties,
// never their names.
type Catalog struct {
	// Boat types.
	Boats []Boat `json:"boats"`
}

// Stable identifier of a kind, stored in the database: never renamed or reused.
type ID string

// Version is the catalog version (tools/catalog).
const Version = "1062915e6cb9a2d8"
