// SPDX-License-Identifier: AGPL-3.0-only

// Command protocol generates the game connection's code from its schema:
// the Go and TypeScript messages, through buf and its two generators, and
// the protocol version both sides send and compare.
//
//	go run ./tools/protocol          generate
//	go run ./tools/protocol -check   generate into a scratch directory and fail if anything committed differs
//
// The protocol version is the first 16 hexadecimal digits of the SHA-256 of
// the schema and of the snapshot's layout, so it changes whenever either
// does. buf comes from the client's packages, so npm ci must have run. It
// runs from the repository root.
package main

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"sort"
	"strings"
)

const (
	schema   = "shared/protocol/keel/v1/game.proto"
	layout   = "shared/protocol/snapshot.txt"
	template = "shared/protocol/buf.gen.yaml"
	buf      = "client/node_modules/.bin/buf"
	goOut    = "internal/protocol/pb"
	tsOut    = "client/src/net/gen"
	goVer    = "internal/protocol/version.gen.go"
	tsVer    = "client/src/net/version.gen.ts"
)

func main() {
	check := flag.Bool("check", false, "write nothing; fail if a generated file is out of date")
	flag.Parse()
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stop()
	var err error
	if *check {
		err = runCheck(ctx, ".")
	} else {
		err = runGenerate(ctx, ".")
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "protocol:", err)
		os.Exit(1)
	}
}

func runGenerate(ctx context.Context, root string) error {
	if err := generate(ctx, root, ""); err != nil {
		return err
	}
	v, err := version(root)
	if err != nil {
		return err
	}
	for path, data := range versionFiles(v) {
		if err := os.WriteFile(filepath.Join(root, path), data, 0o644); err != nil {
			return err
		}
	}
	fmt.Printf("protocol: generated %s and %s; version %s\n", goOut, tsOut, v)
	return nil
}

func runCheck(ctx context.Context, root string) error {
	scratch, err := os.MkdirTemp("", "keel-protocol-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(scratch)
	if err := generate(ctx, root, scratch); err != nil {
		return err
	}
	v, err := version(root)
	if err != nil {
		return err
	}
	for path, data := range versionFiles(v) {
		if err := os.MkdirAll(filepath.Join(scratch, filepath.Dir(path)), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(scratch, path), data, 0o644); err != nil {
			return err
		}
	}
	stale, err := compare(root, scratch, []string{goOut, tsOut, goVer, tsVer})
	if err != nil {
		return err
	}
	if len(stale) > 0 {
		return fmt.Errorf("out of date, run go run ./tools/protocol:\n  %s", strings.Join(stale, "\n  "))
	}
	fmt.Printf("protocol: the generated files are current; version %s\n", v)
	return nil
}

// generate runs buf's generators, into root or, if out is not "", into out
// in the same layout.
func generate(ctx context.Context, root, out string) error {
	args := []string{"generate", "--template", template}
	if out != "" {
		args = append(args, "--output", out)
	}
	cmd := exec.CommandContext(ctx, filepath.Join(root, buf), args...)
	cmd.Dir = root
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("buf generate (has npm ci run in client?): %w", err)
	}
	return nil
}

// version is the protocol version: what both sides must agree on to
// understand each other.
func version(root string) (string, error) {
	h := sha256.New()
	for _, path := range []string{schema, layout} {
		data, err := os.ReadFile(filepath.Join(root, path))
		if err != nil {
			return "", err
		}
		// Each file's name and length come first, so moving text from
		// one to the other changes the version too.
		fmt.Fprintf(h, "%s %d\n", path, len(data))
		h.Write(data)
	}
	return hex.EncodeToString(h.Sum(nil))[:16], nil
}

func versionFiles(v string) map[string][]byte {
	return map[string][]byte{
		goVer: fmt.Appendf(nil, `// SPDX-License-Identifier: AGPL-3.0-only
// Code generated by go run ./tools/protocol. DO NOT EDIT.

package protocol

// Version is the protocol version: a hash of the schema and the snapshot's
// layout. A client's Hello must carry the same.
const Version = %q
`, v),
		tsVer: fmt.Appendf(nil, `// SPDX-License-Identifier: AGPL-3.0-only
// Code generated by go run ./tools/protocol. DO NOT EDIT.

/** The protocol version: a hash of the schema and the snapshot's layout. */
export const PROTOCOL_VERSION = '%s';
`, v),
	}
}

// compare lists the files under each of paths (files or directories) that
// differ between root and generated, or exist in only one of them.
func compare(root, generated string, paths []string) ([]string, error) {
	var stale []string
	for _, p := range paths {
		a, err := listFiles(filepath.Join(root, p))
		if err != nil {
			return nil, err
		}
		b, err := listFiles(filepath.Join(generated, p))
		if err != nil {
			return nil, err
		}
		names := map[string]bool{}
		for n := range a {
			names[n] = true
		}
		for n := range b {
			names[n] = true
		}
		for n := range names {
			da, ina := a[n]
			db, inb := b[n]
			if !ina || !inb || !bytes.Equal(da, db) {
				stale = append(stale, filepath.ToSlash(filepath.Join(p, n)))
			}
		}
	}
	sort.Strings(stale)
	return stale, nil
}

// listFiles reads the files under path, by their path relative to it; a
// file is read as itself, by the name "".
func listFiles(path string) (map[string][]byte, error) {
	files := map[string][]byte{}
	info, err := os.Stat(path)
	if errors.Is(err, fs.ErrNotExist) {
		return files, nil
	}
	if err != nil {
		return nil, err
	}
	if !info.IsDir() {
		data, err := os.ReadFile(path)
		files[""] = data
		return files, err
	}
	err = filepath.WalkDir(path, func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		data, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(path, p)
		files[filepath.ToSlash(rel)] = data
		return nil
	})
	return files, err
}
