// SPDX-License-Identifier: AGPL-3.0-only
// Code generated by go run ./tools/protocol. DO NOT EDIT.

/** The protocol version: a hash of the schema and the snapshot's layout. */
export const PROTOCOL_VERSION = 'ead2021a5942346e';
