// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGuestAccount = `-- name: CreateGuestAccount :one
INSERT INTO account (kind) VALUES ('human')
RETURNING id
`

func (q *Queries) CreateGuestAccount(ctx context.Context) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createGuestAccount)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createSailor = `-- name: CreateSailor :exec
INSERT INTO sailor (account_id, name, name_key, look)
VALUES ($1, $2, $3, $4)
`

type CreateSailorParams struct {
	AccountID pgtype.UUID
	Name      string
	NameKey   string
	Look      string
}

func (q *Queries) CreateSailor(ctx context.Context, arg CreateSailorParams) error {
	_, err := q.db.Exec(ctx, createSailor,
		arg.AccountID,
		arg.Name,
		arg.NameKey,
		arg.Look,
	)
	return err
}
