// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertEvents implements pgx.CopyFromSource.
type iteratorForInsertEvents struct {
	rows                 []InsertEventsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertEvents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertEvents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].WorldID,
		r.rows[0].Tick,
		r.rows[0].Kind,
		r.rows[0].AccountID,
		r.rows[0].Boat,
	}, nil
}

func (r iteratorForInsertEvents) Err() error {
	return nil
}

func (q *Queries) InsertEvents(ctx context.Context, arg []InsertEventsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"event"}, []string{"world_id", "tick", "kind", "account_id", "boat"}, &iteratorForInsertEvents{rows: arg})
}
