// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID         pgtype.UUID
	Kind       string
	OwnerID    pgtype.UUID
	CreatedAt  time.Time
	SavedAt    pgtype.Timestamptz
	LastSeenAt time.Time
}

type Checkpoint struct {
	WorldID   pgtype.UUID
	Tick      int64
	Format    int16
	Build     string
	Catalog   string
	Layout    int32
	Epoch     int64
	Boats     int32
	Data      []byte
	WrittenAt time.Time
}

type Event struct {
	WorldID   pgtype.UUID
	ID        pgtype.UUID
	Tick      int64
	Kind      string
	AccountID pgtype.UUID
	Boat      int64
	WrittenAt time.Time
}

type Sailor struct {
	AccountID pgtype.UUID
	Name      string
	NameKey   string
	Look      string
	CreatedAt time.Time
}

type Session struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	TokenHash  []byte
	CreatedAt  time.Time
	LastSeenAt time.Time
}

type SimLease struct {
	Singleton bool
	Epoch     int64
	Holder    string
	Since     pgtype.Timestamptz
}

type World struct {
	ID        pgtype.UUID
	Number    int32
	Epoch     time.Time
	State     string
	CreatedAt time.Time
}
