// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID         pgtype.UUID
	Kind       string
	OwnerID    pgtype.UUID
	CreatedAt  time.Time
	SavedAt    pgtype.Timestamptz
	LastSeenAt time.Time
}

type Sailor struct {
	AccountID pgtype.UUID
	Name      string
	NameKey   string
	Look      string
	CreatedAt time.Time
}

type Session struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	TokenHash  []byte
	CreatedAt  time.Time
	LastSeenAt time.Time
}

type World struct {
	ID        pgtype.UUID
	Number    int32
	Epoch     time.Time
	State     string
	CreatedAt time.Time
}
