// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: persist.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type InsertEventsParams struct {
	WorldID   pgtype.UUID
	Tick      int64
	Kind      string
	AccountID pgtype.UUID
	Boat      int64
}

const latestCheckpoint = `-- name: LatestCheckpoint :one
SELECT tick, format, build, catalog, layout, epoch, boats, data, written_at
FROM checkpoint WHERE world_id = $1
`

type LatestCheckpointRow struct {
	Tick      int64
	Format    int16
	Build     string
	Catalog   string
	Layout    int32
	Epoch     int64
	Boats     int32
	Data      []byte
	WrittenAt time.Time
}

func (q *Queries) LatestCheckpoint(ctx context.Context, worldID pgtype.UUID) (LatestCheckpointRow, error) {
	row := q.db.QueryRow(ctx, latestCheckpoint, worldID)
	var i LatestCheckpointRow
	err := row.Scan(
		&i.Tick,
		&i.Format,
		&i.Build,
		&i.Catalog,
		&i.Layout,
		&i.Epoch,
		&i.Boats,
		&i.Data,
		&i.WrittenAt,
	)
	return i, err
}

const leaseEpochForShare = `-- name: LeaseEpochForShare :one
SELECT epoch FROM sim_lease FOR SHARE
`

func (q *Queries) LeaseEpochForShare(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, leaseEpochForShare)
	var epoch int64
	err := row.Scan(&epoch)
	return epoch, err
}

const leaseHolder = `-- name: LeaseHolder :one
SELECT epoch, holder, since FROM sim_lease
`

type LeaseHolderRow struct {
	Epoch  int64
	Holder string
	Since  pgtype.Timestamptz
}

func (q *Queries) LeaseHolder(ctx context.Context) (LeaseHolderRow, error) {
	row := q.db.QueryRow(ctx, leaseHolder)
	var i LeaseHolderRow
	err := row.Scan(&i.Epoch, &i.Holder, &i.Since)
	return i, err
}

const raiseLeaseEpoch = `-- name: RaiseLeaseEpoch :one
UPDATE sim_lease SET epoch = epoch + 1, holder = $1, since = now()
RETURNING epoch
`

func (q *Queries) RaiseLeaseEpoch(ctx context.Context, holder string) (int64, error) {
	row := q.db.QueryRow(ctx, raiseLeaseEpoch, holder)
	var epoch int64
	err := row.Scan(&epoch)
	return epoch, err
}

const releaseLease = `-- name: ReleaseLease :one
SELECT pg_advisory_unlock($1::bigint)
`

func (q *Queries) ReleaseLease(ctx context.Context, key int64) (bool, error) {
	row := q.db.QueryRow(ctx, releaseLease, key)
	var pg_advisory_unlock bool
	err := row.Scan(&pg_advisory_unlock)
	return pg_advisory_unlock, err
}

const tryLease = `-- name: TryLease :one
SELECT pg_try_advisory_lock($1::bigint)
`

func (q *Queries) TryLease(ctx context.Context, key int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryLease, key)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}

const upsertCheckpoint = `-- name: UpsertCheckpoint :exec
INSERT INTO checkpoint (world_id, tick, format, build, catalog, layout, epoch, boats, data, written_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
ON CONFLICT (world_id) DO UPDATE SET
  tick = excluded.tick, format = excluded.format, build = excluded.build, catalog = excluded.catalog,
  layout = excluded.layout, epoch = excluded.epoch, boats = excluded.boats, data = excluded.data,
  written_at = excluded.written_at
`

type UpsertCheckpointParams struct {
	WorldID pgtype.UUID
	Tick    int64
	Format  int16
	Build   string
	Catalog string
	Layout  int32
	Epoch   int64
	Boats   int32
	Data    []byte
}

func (q *Queries) UpsertCheckpoint(ctx context.Context, arg UpsertCheckpointParams) error {
	_, err := q.db.Exec(ctx, upsertCheckpoint,
		arg.WorldID,
		arg.Tick,
		arg.Format,
		arg.Build,
		arg.Catalog,
		arg.Layout,
		arg.Epoch,
		arg.Boats,
		arg.Data,
	)
	return err
}
