// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO session (account_id, token_hash)
VALUES ($1, $2)
`

type CreateSessionParams struct {
	AccountID pgtype.UUID
	TokenHash []byte
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.AccountID, arg.TokenHash)
	return err
}

const sessionAccount = `-- name: SessionAccount :one
SELECT a.id, a.kind, (a.saved_at IS NOT NULL)::boolean AS saved, sl.name, sl.look, s.last_seen_at
FROM session s
JOIN account a ON a.id = s.account_id
JOIN sailor sl ON sl.account_id = a.id
WHERE s.token_hash = $1
`

type SessionAccountRow struct {
	ID         pgtype.UUID
	Kind       string
	Saved      bool
	Name       string
	Look       string
	LastSeenAt time.Time
}

func (q *Queries) SessionAccount(ctx context.Context, tokenHash []byte) (SessionAccountRow, error) {
	row := q.db.QueryRow(ctx, sessionAccount, tokenHash)
	var i SessionAccountRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Saved,
		&i.Name,
		&i.Look,
		&i.LastSeenAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
WITH s AS (
  UPDATE session SET last_seen_at = now()
  WHERE token_hash = $1
  RETURNING account_id
)
UPDATE account SET last_seen_at = now()
WHERE id IN (SELECT account_id FROM s)
`

func (q *Queries) TouchSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, touchSession, tokenHash)
	return err
}
