// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worlds.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeWorld = `-- name: ActiveWorld :one
SELECT id, number, epoch FROM world WHERE state = 'active'
`

type ActiveWorldRow struct {
	ID     pgtype.UUID
	Number int32
	Epoch  time.Time
}

func (q *Queries) ActiveWorld(ctx context.Context) (ActiveWorldRow, error) {
	row := q.db.QueryRow(ctx, activeWorld)
	var i ActiveWorldRow
	err := row.Scan(&i.ID, &i.Number, &i.Epoch)
	return i, err
}

const createWorldPartitions = `-- name: CreateWorldPartitions :exec
SELECT create_world_partitions($1)
`

func (q *Queries) CreateWorldPartitions(ctx context.Context, worldID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, createWorldPartitions, worldID)
	return err
}

const insertWorld = `-- name: InsertWorld :one
INSERT INTO world (number, epoch, state)
VALUES ((SELECT coalesce(max(number), 0) + 1 FROM world), $1, 'active')
RETURNING id, number, epoch
`

type InsertWorldRow struct {
	ID     pgtype.UUID
	Number int32
	Epoch  time.Time
}

func (q *Queries) InsertWorld(ctx context.Context, epoch time.Time) (InsertWorldRow, error) {
	row := q.db.QueryRow(ctx, insertWorld, epoch)
	var i InsertWorldRow
	err := row.Scan(&i.ID, &i.Number, &i.Epoch)
	return i, err
}
