// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by go run ./tools/physics. DO NOT EDIT.

package physics

// LayoutVersion identifies the layout of the records and the list of Fn. The
// WebAssembly module reports it, and the client refuses a module whose
// version differs from its own copy in client/src/predict/layout.gen.ts.
const LayoutVersion uint32 = 0x2457976f
