// SPDX-License-Identifier: AGPL-3.0-only
// Code generated by go run ./tools/protocol. DO NOT EDIT.

package protocol

// Version is the protocol version: a hash of the schema and the snapshot's
// layout. A client's Hello must carry the same.
const Version = "6dddcdcf3fd8959a"
