// SPDX-License-Identifier: AGPL-3.0-only

package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"go/format"
	"reflect"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/daneelvt/keel-over-the-edge/internal/physics"
)

// The records the module exposes, by the name of the export that returns
// each one's address.
var records = []struct {
	name string
	typ  reflect.Type
}{
	{"state", reflect.TypeFor[physics.State]()},
	{"control", reflect.TypeFor[physics.Control]()},
	{"env", reflect.TypeFor[physics.Env]()},
	{"params", reflect.TypeFor[physics.Params]()},
}

type recordLayout struct {
	name   string
	fields []string
}

// layout is what the client must agree on with the module.
type layout struct {
	records []recordLayout
	fns     []string
	version uint32
}

// describe reads the records and the functions from the physics package.
func describe() (layout, error) {
	var l layout
	for _, r := range records {
		rl := recordLayout{name: r.name}
		for i := range r.typ.NumField() {
			f := r.typ.Field(i)
			if f.Type.Kind() != reflect.Float64 {
				return layout{}, fmt.Errorf("%s.%s is %s; every field of a record must be a float64", r.typ.Name(), f.Name, f.Type)
			}
			if f.Offset != uintptr(8*i) {
				return layout{}, fmt.Errorf("%s.%s is at offset %d, not %d", r.typ.Name(), f.Name, f.Offset, 8*i)
			}
			rl.fields = append(rl.fields, jsName(f.Name))
		}
		l.records = append(l.records, rl)
	}
	l.fns = physics.FnNames[:]
	l.version = versionOf(l)
	return l, nil
}

// jsName is a Go field name as the client spells it: YawRate is yawRate.
func jsName(goName string) string {
	r, n := utf8.DecodeRuneInString(goName)
	return string(unicode.ToLower(r)) + goName[n:]
}

// versionOf is the first four bytes of the SHA-256 of the layout's text.
func versionOf(l layout) uint32 {
	var b strings.Builder
	for _, r := range l.records {
		fmt.Fprintf(&b, "%s:%s\n", r.name, strings.Join(r.fields, ","))
	}
	fmt.Fprintf(&b, "fn:%s\n", strings.Join(l.fns, ","))
	sum := sha256.Sum256([]byte(b.String()))
	return binary.BigEndian.Uint32(sum[:4])
}

func (l layout) files() map[string][]byte {
	return map[string][]byte{goLayout: l.goFile(), tsLayout: l.tsFile()}
}

func (l layout) goFile() []byte {
	src := fmt.Sprintf(`// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by go run ./tools/physics. DO NOT EDIT.

package physics

// LayoutVersion identifies the layout of the records and the list of Fn. The
// WebAssembly module reports it, and the client refuses a module whose
// version differs from its own copy in client/src/predict/layout.gen.ts.
const LayoutVersion uint32 = %#08x
`, l.version)
	out, err := format.Source([]byte(src))
	if err != nil {
		panic(err) // the template above is valid Go
	}
	return out
}

func (l layout) tsFile() []byte {
	var b bytes.Buffer
	b.WriteString(`// SPDX-License-Identifier: AGPL-3.0-only
// Code generated by go run ./tools/physics. DO NOT EDIT.

/** Version of the records' layout; the physics module must report the same. */
`)
	fmt.Fprintf(&b, "export const LAYOUT_VERSION = %#08x;\n\n", l.version)
	b.WriteString(`/**
 * The physics module's records, each named by the export that returns its
 * address, with the index of each field in a Float64Array laid over it.
 */
export const RECORDS = {
`)
	for _, r := range l.records {
		fmt.Fprintf(&b, "  %s: {", r.name)
		for i, f := range r.fields {
			sep := ","
			if i == len(r.fields)-1 {
				sep = ""
			}
			fmt.Fprintf(&b, " %s: %d%s", f, i, sep)
		}
		b.WriteString(" },\n")
	}
	b.WriteString("} as const;\n\n/** Codes of the functions the module's fn export evaluates. */\nexport const FN = {")
	for i, f := range l.fns {
		sep := ","
		if i == len(l.fns)-1 {
			sep = ""
		}
		fmt.Fprintf(&b, " %s: %d%s", f, i, sep)
	}
	b.WriteString(" } as const;\n")
	return b.Bytes()
}
