// SPDX-License-Identifier: AGPL-3.0-only

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/daneelvt/keel-over-the-edge/internal/physics"
)

// A boat's physics values go from the catalog into the physics package's
// Params record: on the server by catalog.PhysicsParams, in the client by
// writeParams, which writes them into the WebAssembly module's memory. Both
// are generated here from the schema, and the schema's fields are checked
// against Params field for field, so the three cannot drift.

const (
	goPhysicsPath = "internal/catalog/physics.gen.go"
	tsParamsPath  = "client/src/predict/params.gen.ts"
	physicsDef    = "BoatPhysics"
)

// physicsField is one value of a boat's physics object.
type physicsField struct {
	group, name string // as in the catalog: hull, displacement
	length      int    // for an array, its fixed length; 0 for a number
}

// physicsFields reads the physics object's fields from the schema, in the
// order of its required lists, which is the order of Params.
func physicsFields(root string) ([]physicsField, error) {
	raw, err := os.ReadFile(filepath.Join(root, schemaPath))
	if err != nil {
		return nil, err
	}
	type def struct {
		Required   []string `json:"required"`
		Properties map[string]struct {
			Ref      string `json:"$ref"`
			Type     string `json:"type"`
			MinItems int    `json:"minItems"`
			MaxItems int    `json:"maxItems"`
		} `json:"properties"`
	}
	var schema struct {
		Defs map[string]def `json:"$defs"`
	}
	if err := json.Unmarshal(raw, &schema); err != nil {
		return nil, fmt.Errorf("%s: %w", schemaPath, err)
	}
	top, ok := schema.Defs[physicsDef]
	if !ok {
		return nil, fmt.Errorf("%s has no %s", schemaPath, physicsDef)
	}
	var fields []physicsField
	for _, group := range top.Required {
		ref := top.Properties[group].Ref
		g, ok := schema.Defs[strings.TrimPrefix(ref, "#/$defs/")]
		if !ok {
			return nil, fmt.Errorf("%s.%s refers to %q, which is not defined", physicsDef, group, ref)
		}
		if len(g.Required) != len(g.Properties) {
			return nil, fmt.Errorf("%s: every value of the physics group %s must be required", schemaPath, group)
		}
		for _, name := range g.Required {
			prop, ok := g.Properties[name]
			if !ok {
				return nil, fmt.Errorf("%s: physics group %s requires %s, which it does not define", schemaPath, group, name)
			}
			f := physicsField{group: group, name: name}
			switch prop.Type {
			case "number":
			case "array":
				if prop.MinItems != prop.MaxItems || prop.MaxItems == 0 {
					return nil, fmt.Errorf("%s: physics array %s.%s must have a fixed length", schemaPath, group, name)
				}
				f.length = prop.MaxItems
			default:
				return nil, fmt.Errorf("%s: physics value %s.%s must be a number or an array of numbers", schemaPath, group, name)
			}
			fields = append(fields, f)
		}
	}
	return fields, nil
}

// checkParams fails unless Params has exactly the schema's fields, in order,
// with the same array lengths.
func checkParams(fields []physicsField) error {
	t := reflect.TypeFor[physics.Params]()
	var problems []string
	for i := range max(t.NumField(), len(fields)) {
		switch {
		case i >= len(fields):
			problems = append(problems, fmt.Sprintf("  Params.%s is not in the schema", t.Field(i).Name))
		case i >= t.NumField():
			problems = append(problems, fmt.Sprintf("  the schema's %s.%s is not in Params", fields[i].group, fields[i].name))
		default:
			sf, f := t.Field(i), fields[i]
			length := 0
			if sf.Type.Kind() == reflect.Array {
				length = sf.Type.Len()
			}
			if sf.Name != goName(f.name) || length != f.length {
				problems = append(problems, fmt.Sprintf("  field %d: Params has %s %s, the schema %s.%s%s",
					i, sf.Name, sf.Type, f.group, f.name, lengthNote(f.length)))
			}
		}
	}
	if len(problems) > 0 {
		return fmt.Errorf("internal/physics Params does not match the schema's %s, field for field:\n%s",
			physicsDef, strings.Join(problems, "\n"))
	}
	return nil
}

func lengthNote(n int) string {
	if n == 0 {
		return ""
	}
	return fmt.Sprintf(" (%d values)", n)
}

// goName is a schema property as Go spells it: dragArea is DragArea.
func goName(name string) string {
	r, n := utf8.DecodeRuneInString(name)
	return string(unicode.ToUpper(r)) + name[n:]
}

func goPhysics(fields []physicsField) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, `// %s

// Code generated by tools/catalog from %s. DO NOT EDIT.

package catalog

import "github.com/daneelvt/keel-over-the-edge/internal/physics"

// PhysicsParams returns a boat's physics values as the physics package's
// Params.
func PhysicsParams(b *Boat) physics.Params {
	var p physics.Params
`, spdx, schemaPath)
	for _, f := range fields {
		from := fmt.Sprintf("b.Physics.%s.%s", goName(f.group), goName(f.name))
		if f.length > 0 {
			fmt.Fprintf(&b, "\tcopy(p.%s[:], %s)\n", goName(f.name), from)
		} else {
			fmt.Fprintf(&b, "\tp.%s = %s\n", goName(f.name), from)
		}
	}
	b.WriteString("\treturn p\n}\n")
	return format.Source(b.Bytes())
}

func tsParams(fields []physicsField) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, `// %s
// Code generated by tools/catalog from %s. DO NOT EDIT.

import type { BoatPhysics } from '../catalog/types.gen';
import { RECORDS } from './layout.gen';

/**
 * Writes a boat's physics values from the catalog into the physics module's
 * Params record. The module's prepare export derives everything else.
 */
export function writeParams(params: Float64Array, p: BoatPhysics): void {
  const f = RECORDS.params;
`, spdx, schemaPath)
	for _, f := range fields {
		if f.length > 0 {
			fmt.Fprintf(&b, "  params.set(p.%s.%s, f.%s);\n", f.group, f.name, f.name)
		} else {
			fmt.Fprintf(&b, "  params[f.%s] = p.%s.%s;\n", f.name, f.group, f.name)
		}
	}
	b.WriteString("}\n")
	return b.Bytes()
}
