// SPDX-License-Identifier: AGPL-3.0-only
// Code generated by go run ./tools/physics. DO NOT EDIT.

/** Version of the records' layout; the physics module must report the same. */
export const LAYOUT_VERSION = 0x51dae061;

/**
 * The physics module's records, each named by the export that returns its
 * address, with the index of each field in a Float64Array laid over it.
 */
export const RECORDS = {
  state: { x: 0, y: 1, heading: 2, surge: 3, sway: 4, yawRate: 5 },
  control: { helm: 0, trim: 1 },
  env: { windSpeed: 0, windFrom: 1 },
  params: { mass: 0, yawInertia: 1, sailArea: 2, sailHeight: 3, dragAhead: 4, dragSide: 5, rudderPower: 6, yawDamping: 7 },
} as const;

/** Codes of the functions the module's fn export evaluates. */
export const FN = { sin: 0, cos: 1, exp: 2, log: 3, atan: 4, atan2: 5 } as const;
