// SPDX-License-Identifier: AGPL-3.0-only
// Code generated by go run ./tools/physics. DO NOT EDIT.

/** Version of the records' layout; the physics module must report the same. */
export const LAYOUT_VERSION = 0x2457976f;

/**
 * The physics module's records, each named by the export that returns its
 * address, with the index of each field in a Float64Array laid over it. For
 * an array, the index of its first value.
 */
export const RECORDS = {
  state: { x: 0, y: 1, heading: 2, surge: 3, sway: 4, yawRate: 5, heel: 6, rollRate: 7, boom: 8, boomRate: 9, sailor: 10, rudder: 11, sheetLimit: 12, sailorMode: 13, sailorTimer: 14 },
  control: { helm: 0, sheet: 1 },
  env: { windSpeed: 0, windFrom: 1 },
  params: { displacement: 0, waterlineLength: 1, hullDraught: 2, centreOfGravity: 3, dragAreaStep: 4, dragArea: 5, crossFlowDrag: 30, addedMassSurge: 31, addedMassSway: 32, munk: 33, yawInertia: 34, rollInertia: 35, rollDamping: 36, rightingLever: 37, sailArea: 56, luff: 57, foot: 58, boomHeight: 59, mastPosition: 60, footStrip: 61, headStrip: 62, pressureAttached: 63, pressureSeparated: 64, effectiveHeight: 65, quadraticDrag: 66, maxLift: 67, stallAngle: 68, stallWidth: 69, sailDrag: 70, luffAngle: 71, flogDrag: 72, normalForce: 73, twistPowered: 92, twistDepowered: 93, twistEased: 94, twistTurn: 95, headBacked: 96, headBackedWidth: 97, boomIn: 98, boomOut: 99, boomInertia: 100, boomMoment: 101, boomDamping: 102, windageFront: 103, windageSide: 104, windageHeight: 105, sailFloat: 106, sailWaterDamping: 107, boardSpan: 108, boardChord: 109, boardPosition: 110, rudderSpan: 111, rudderChord: 112, rudderPosition: 113, rudderAngle: 114, foilStall: 115, foilStallWidth: 116, foilDrag: 117, plateNormal: 118, pressureDepth: 119, carryOver: 120, heelLoss: 121, rudderInflow: 122, downwash: 123, foilWetHeel: 124, foilDryHeel: 125, sailorMass: 126, sailorSeatHeight: 127, hikeReach: 128, leeReach: 129, hikeSpeed: 130, hikeLag: 131, heelGain: 132, rollRateGain: 133, flattenFrom: 134, flattenTo: 135, flattenMin: 136, fallOutHeel: 137, climbInHeel: 138, boardReach: 139, sailorDrag: 140, swimTime: 141, climbTime: 142, rudderTime: 143, sheetHaulTime: 144, sheetEaseTime: 145 },
  out: { apparentWindSpeed: 0, apparentWindAngle: 1, sailWindSpeed: 2, sailWindAngle: 3, footAttack: 4, headAttack: 5, footFlow: 6, headFlow: 7, drive: 8, sideForce: 9, boardLift: 10, rudderLift: 11, leeway: 12, speedOverGround: 13, courseOverGround: 14, heelingMoment: 15, rightingMoment: 16, flattening: 17, twist: 18 },
} as const;

/** The length of each array field, which RECORDS gives the first index of. */
export const ARRAYS = {
  state: {},
  control: {},
  env: {},
  params: { dragArea: 25, rightingLever: 19, normalForce: 19 },
  out: {},
} as const;

/** Each record's length in float64s. */
export const SIZES = { state: 15, control: 2, env: 2, params: 146, out: 19 } as const;

/** Codes of the functions the module's fn export evaluates. */
export const FN = { sin: 0, cos: 1, exp: 2, log: 3, atan: 4, atan2: 5 } as const;
