// SPDX-License-Identifier: AGPL-3.0-only
// Code generated by tools/catalog from shared/catalog.schema.json. DO NOT EDIT.

import type { BoatPhysics } from '../catalog/types.gen';
import { RECORDS } from './layout.gen';

/**
 * Writes a boat's physics values from the catalog into the physics module's
 * Params record. The module's prepare export derives everything else.
 */
export function writeParams(params: Float64Array, p: BoatPhysics): void {
  const f = RECORDS.params;
  params[f.displacement] = p.hull.displacement;
  params[f.waterlineLength] = p.hull.waterlineLength;
  params[f.hullDraught] = p.hull.hullDraught;
  params[f.centreOfGravity] = p.hull.centreOfGravity;
  params[f.dragAreaStep] = p.hull.dragAreaStep;
  params.set(p.hull.dragArea, f.dragArea);
  params[f.crossFlowDrag] = p.hull.crossFlowDrag;
  params[f.addedMassSurge] = p.hull.addedMassSurge;
  params[f.addedMassSway] = p.hull.addedMassSway;
  params[f.munk] = p.hull.munk;
  params[f.yawInertia] = p.hull.yawInertia;
  params[f.rollInertia] = p.hull.rollInertia;
  params[f.rollDamping] = p.hull.rollDamping;
  params.set(p.hull.rightingLever, f.rightingLever);
  params[f.sailArea] = p.rig.sailArea;
  params[f.luff] = p.rig.luff;
  params[f.foot] = p.rig.foot;
  params[f.boomHeight] = p.rig.boomHeight;
  params[f.mastPosition] = p.rig.mastPosition;
  params[f.footStrip] = p.rig.footStrip;
  params[f.headStrip] = p.rig.headStrip;
  params[f.pressureAttached] = p.rig.pressureAttached;
  params[f.pressureSeparated] = p.rig.pressureSeparated;
  params[f.effectiveHeight] = p.rig.effectiveHeight;
  params[f.quadraticDrag] = p.rig.quadraticDrag;
  params[f.maxLift] = p.rig.maxLift;
  params[f.stallAngle] = p.rig.stallAngle;
  params[f.stallWidth] = p.rig.stallWidth;
  params[f.sailDrag] = p.rig.sailDrag;
  params[f.luffAngle] = p.rig.luffAngle;
  params[f.flogDrag] = p.rig.flogDrag;
  params.set(p.rig.normalForce, f.normalForce);
  params[f.twistPowered] = p.rig.twistPowered;
  params[f.twistDepowered] = p.rig.twistDepowered;
  params[f.twistEased] = p.rig.twistEased;
  params[f.twistTurn] = p.rig.twistTurn;
  params[f.headBacked] = p.rig.headBacked;
  params[f.headBackedWidth] = p.rig.headBackedWidth;
  params[f.boomIn] = p.rig.boomIn;
  params[f.boomOut] = p.rig.boomOut;
  params[f.boomInertia] = p.rig.boomInertia;
  params[f.boomMoment] = p.rig.boomMoment;
  params[f.boomDamping] = p.rig.boomDamping;
  params[f.windageFront] = p.rig.windageFront;
  params[f.windageSide] = p.rig.windageSide;
  params[f.windageHeight] = p.rig.windageHeight;
  params[f.sailFloat] = p.rig.sailFloat;
  params[f.sailWaterDamping] = p.rig.sailWaterDamping;
  params[f.boardSpan] = p.foils.boardSpan;
  params[f.boardChord] = p.foils.boardChord;
  params[f.boardPosition] = p.foils.boardPosition;
  params[f.rudderSpan] = p.foils.rudderSpan;
  params[f.rudderChord] = p.foils.rudderChord;
  params[f.rudderPosition] = p.foils.rudderPosition;
  params[f.rudderAngle] = p.foils.rudderAngle;
  params[f.foilStall] = p.foils.foilStall;
  params[f.foilStallWidth] = p.foils.foilStallWidth;
  params[f.foilDrag] = p.foils.foilDrag;
  params[f.plateNormal] = p.foils.plateNormal;
  params[f.pressureDepth] = p.foils.pressureDepth;
  params[f.carryOver] = p.foils.carryOver;
  params[f.heelLoss] = p.foils.heelLoss;
  params[f.rudderInflow] = p.foils.rudderInflow;
  params[f.downwash] = p.foils.downwash;
  params[f.foilWetHeel] = p.foils.foilWetHeel;
  params[f.foilDryHeel] = p.foils.foilDryHeel;
  params[f.sailorMass] = p.sailor.sailorMass;
  params[f.sailorSeatHeight] = p.sailor.sailorSeatHeight;
  params[f.hikeReach] = p.sailor.hikeReach;
  params[f.leeReach] = p.sailor.leeReach;
  params[f.hikeSpeed] = p.sailor.hikeSpeed;
  params[f.hikeLag] = p.sailor.hikeLag;
  params[f.heelGain] = p.sailor.heelGain;
  params[f.rollRateGain] = p.sailor.rollRateGain;
  params[f.flattenFrom] = p.sailor.flattenFrom;
  params[f.flattenTo] = p.sailor.flattenTo;
  params[f.flattenMin] = p.sailor.flattenMin;
  params[f.fallOutHeel] = p.sailor.fallOutHeel;
  params[f.climbInHeel] = p.sailor.climbInHeel;
  params[f.boardReach] = p.sailor.boardReach;
  params[f.sailorDrag] = p.sailor.sailorDrag;
  params[f.swimTime] = p.sailor.swimTime;
  params[f.climbTime] = p.sailor.climbTime;
  params[f.rudderTime] = p.rates.rudderTime;
  params[f.sheetHaulTime] = p.rates.sheetHaulTime;
  params[f.sheetEaseTime] = p.rates.sheetEaseTime;
}
